"""empty message

Revision ID: 2b1d849f6c9c
Revises: 6d0e4cd829ae
Create Date: 2024-08-29 22:48:42.243882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1d849f6c9c'
down_revision = '6d0e4cd829ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.String(length=3072),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.String(length=3072),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.String(length=3072),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=3072),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=False)

    # ### end Alembic commands ###
