"""empty message

Revision ID: 55aa51317a74
Revises: 6bd8d30cb837
Create Date: 2024-08-20 18:45:09.690003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55aa51317a74'
down_revision = '6bd8d30cb837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.VARCHAR(length=4096),
               nullable=True)
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_seen',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('about',
               existing_type=sa.VARCHAR(length=4096),
               nullable=False)

    # ### end Alembic commands ###
