"""empty message

Revision ID: 63ff6249f391
Revises: 8da7f868824a
Create Date: 2024-08-20 18:28:30.885386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ff6249f391'
down_revision = '8da7f868824a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String(length=4096), nullable=False))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_about'), ['about'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_last_seen'), ['last_seen'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_last_seen'))
        batch_op.drop_index(batch_op.f('ix_user_about'))
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about')

    # ### end Alembic commands ###
