"""empty message

Revision ID: 6bd8d30cb837
Revises: 63ff6249f391
Create Date: 2024-08-20 18:30:55.722704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd8d30cb837'
down_revision = '63ff6249f391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_about')
        batch_op.drop_index('ix_user_last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_last_seen', ['last_seen'], unique=False)
        batch_op.create_index('ix_user_about', ['about'], unique=1)

    # ### end Alembic commands ###
