"""empty message

Revision ID: a86962b11a87
Revises: 2b1d849f6c9c
Create Date: 2024-09-02 23:41:00.048103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86962b11a87'
down_revision = '2b1d849f6c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activated', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_activated'), ['activated'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activated'))
        batch_op.drop_column('activated')

    # ### end Alembic commands ###
